name: top_alert_notification
description: This package creates a top notification centered in the screen. When presented, you can pass in a child widget, a function for onTap, as well as enable a dismiss button. It also supports a swipe up to dimiss option.
version: 0.0.2
author: Jesse Anderson
homepage: https://github.com/jessecanderson/top_alert_notification

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
