name: top_alert_notification
description: Present a flexible overlay on the top part of a view.
version: 0.0.1
homepage: https://github.com/jessecanderson/top_alert_notification

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
